import Head from 'next/head';
import { Inter } from '@next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Pro Tags</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={inter.className}>
        <div className='container mx-auto transition-transform'>

          <h1 className="text-3xl font-bold underline">
            Hello pro!
          </h1>

          <div className='columns-1'>
            {[1, 2, 3, 4, 5, 6].map((e, index) => {
              return (
                <div className='border rounded p-5 my-5 hover:shadow-lg' id={index === 3 ? 'proadsa' : ''} key={index}>
                  While there are a number of reasons you may want to create random adjectives, one of the most common is writers looking for new ways to better describe their writing. The great thing about this adjective tool is that it can help spark creative juices just by generating new adjectives. Simply seeing a random adjective can spark the imagination to come up with the perfect vocabulary for your writing. If nothing else, this tool will give you options you likely had never considered which in itself can be a great help.
                  This free calculator is also an excellent way to improve your creative writing. A fun and easy way to challenge yourself is to generate a random adjective and then use it in a paragraph. Writers can expand on this and generate 5 to 10 adjectives and write a page or short story using all of them. Since what will be generated is unknown, it forces the writer to use creativity to use the adjectives to make a great paragraph or short story.
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
}
